### PR TITLE
functions

### PR DESCRIPTION
**Pull request by JakeSteinebronn**
- onCreate for user to add them to the username cache

### CODE REVIEW

**Comment by Henry-Graves** [comment]
if we're abandoning this should we go ahead and close it?

**Comment by TylerMathis** [comment]
> if we're abandoning this should we go ahead and close it?

+1, what is the status on this PR

**Comment by JakeSteinebronn** [comment]
No, because we'll likely need cloud functions at some point in time later, so we might as well keep this commit which has all the structure of the functions set up and such

**Comment by JakeSteinebronn** [comment]
We can always reopen it, idk why it's still here

**Pull request closed without merging**
