### PR TITLE
Add the `shouldBeHidden` fields to fetched objects

### LINKED ISSUE #209: Include `shouldBeHidden` in fetched objects
Fetched objects should include the should be hidden field so we don't have to do any async work on FE

### PR DESCRIPTION
**Pull request by tylerhm**
# Describe your changes

_Draft until #208 is merged_
For the first time ever, TSIA is sufficient.

# Issue ticket number and link
closes #209

### CODE REVIEW

**Comment by JakeSteinebronn** [comment]
what about on user?

**Comment by tylerhm** [comment]
> what about on user?

Don't think user's have this field yet?

**Comment by Henry-Graves** [comment]
> > what about on user?
> 
> Don't think user's have this field yet?

it's being added in #208

**Comment by JakeSteinebronn** [comment]
What's the status of this PR

**Comment by tylerhm** [comment]
Reopened as #208 is merged, and functionality is ready :D

**Review by Henry-Graves — APPROVED** [review]
lgtm, all shouldBeHiddens should work now

**Pull request merged**
