### PR TITLE
Add support for mocked types

### PR DESCRIPTION
**Pull request by TylerMathis**
In development environments, we often find ourselves without `docRef`s to fetch for testing objects. This branch adds support for mocked types.

1. Abstract the data fetch into the `LazyObject`, return a `Promise`. Adjust callees to use new API
2. Create Mock objects for all types. Support modification of data for dynamic tests.

### CODE REVIEW

**Comment by TylerMathis** [comment]
Requested review from all, as this functionality impacts all areas.

**Review by abrugal — APPROVED** [review]
I love Mocks. LGTM

**Comment by JakeSteinebronn** [comment]
Not a huge fan of changing the parent class for the purpose of mocking. If it's the only way, we can merge this; I'd like to see if I can come up with something better, though. Please don't merge this for now?

**Comment by TylerMathis** [comment]
For sure. I thought about it for a while and couldn't think of any other way to handle things.

The only difference in the API is the ability for the constructor to provide no arguments, which constructs a mock object. I think the only other option would be to build entirely new classes.

**Pull request merged**
